# Flutter Localizations Config File
synthetic-package: false

# Where input files are located
arb-dir: lib/l10n

# The input file template
template-arb-file: app_en.arb

# Where generated localizations are placed
output-localization-file: app_localizations.dart

nullable-getter: false

# When enabled, the parser ignores text included in a pair of single quotes. If you want to use a single quote in the text, you need to use pairs of single quotes to escape it.
# see https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#escaping-syntax
use-escaping: true